---
services:
  app:
    build: .
    image: ghcr.io/yegor-usoltsev/noom-sleep-logger:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sleep
      SPRING_DATASOURCE_USERNAME: sleep
      SPRING_DATASOURCE_PASSWORD: sleep
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - app

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: sleep
      POSTGRES_USER: sleep
      POSTGRES_PASSWORD: sleep
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sleep" ]
      interval: 5s
      retries: 5
