---
name: CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: sleep
          POSTGRES_USER: sleep
          POSTGRES_PASSWORD: sleep
        ports:
          - "5432:5432"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: ./gradlew build

      - name: Generate Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/yegor-usoltsev/noom-sleep-logger

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
